name : Nicarali
brand : Nicarali
description : "Nicarali est une association qui opère pour la création d'un réseau de bibliothèques publiques au Nicaragua."
keyword : Nicarali, Nicaragua, bibliothèque, association
url : https://drventisette.github.io
email : drventisette@gmail.com
github : drventisette
facebook: nicarali
author : drventisette
analytics : UA-67806526-1
year : 2015
markdown : kramdown
exclude :
  - node_modules
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
paginate: 20
paginate_path: "/archive/page:num"

defaults:
  -
    scope:
      path: _posts/fr
    values:
      layout: post
      lang: fr
  -
    scope:
      path: _posts/es
    values:
      layout: post
      lang: es
